### ISSUE TITLE
Can't get attribute 'evaluate_agent_weights

### ISSUE THREAD

**Issue by tgfred** [Nikolay-Lysenko/rl-musician#6]
Hi I get this error.
i use "python -m rlmusician"
Can this be run on win10?

> Process SpawnPoolWorker-35:
Traceback (most recent call last):
  File "C:\Users\b8950\Anaconda3\envs\tf2.3.7\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\b8950\Anaconda3\envs\tf2.3.7\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\b8950\Anaconda3\envs\tf2.3.7\lib\multiprocessing\pool.py", line 110, in worker
    task = get()
  File "C:\Users\b8950\Anaconda3\envs\tf2.3.7\lib\multiprocessing\queues.py", line 354, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'evaluate_agent_weights' on <module '__main__' (built-in)>

**Comment by Nikolay-Lysenko** [comment]
Hello, **tgfred**!

I apologize for the late reply. I've tested the project on Ubuntu and Mac OS. Currently, I have no experience in using Python multiprocessing on Windows, and so I can not help you.

Your traceback looks like a Windows-specific issue with either running Python module as a script or using Python multiprocessing.
